import copy
import time

import aiofiles

from .. import *
from .image import tricolor_gradient, tricolor_gradient_prism_plus, generate_frosted_card
from .maimai_best_50 import *
from .maimaidx_music import Music, mai


async def update_rating_table() -> str:
    """更新定数表"""
    try:
        if maiApi.config.saveinmem and not ScoreBaseImage.aurora_bg:
            ScoreBaseImage._load_image()
        sbi = ScoreBaseImage if maiApi.config.saveinmem else ScoreBaseImage()
        # 难度色框
        border_names = ['border_basic', 'border_advanced', 'border_expert', 'border_master', 'border_remaster']
        table_diff_bg = [Image.open(maimaidir / f'{n}.png').convert('RGBA') for n in border_names]
        atime = 0
        for lv in levelList[6:]:
            _otime = time.time()
            picname = ratingdir / f'{lv}.png'
            lvlist = mai.total_level_data[lv]

            # 计算高度（仿原项目：START_Y 450 起，逐组累加）
            current_y = 450
            for songs in lvlist.values():
                if not songs:
                    continue
                rows = (len(songs) - 1) // 14 + 1
                current_y += rows * 85 + 30
            height = current_y + 230

            im = tricolor_gradient_prism_plus(1400, height)
            
            im.alpha_composite(sbi.aurora_bg)
            im.alpha_composite(sbi.shines_bg, (11, 6))
            im.alpha_composite(sbi.rainbow_bg, (318, height - 545))
            im.alpha_composite(sbi.rainbow_bottom_bg, (122, height - 305))
            for h in range((height // 358) + 1):
                im.alpha_composite(sbi.pattern_bg, (0, (358 + 7) * h))
            # 分隔线
            separator = maimaidir / 'separator.png'
            if separator.exists():
                im.alpha_composite(Image.open(separator).convert('RGBA'), (100, 360))
            # 毛玻璃卡片
            im = generate_frosted_card(im, (50, 404, 1350, height - 120))

            dr = ImageDraw.Draw(im)
            fn = DrawText(dr, FOTNEWRODIN)
            tb = DrawText(dr, TBFONT)
            fn.draw(
                700, 
                height - 75, 
                30, 
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {get_botname()} BOT', 
                sbi.text_color, 
                'mm'
            )
            START_Y = 450
            for _lv, songs in lvlist.items():
                if not songs:
                    continue
                _ds = _lv.split('.')[-1]
                fn.draw(70, START_Y + 35, 40, f'.{_ds}', sbi.text_color, 'lm', 4, (255, 255, 255, 255))
                max_row = 0
                for num, music in enumerate(songs):
                    row, col = divmod(num, 14)
                    max_row = max(max_row, row)
                    x = 140 + col * 85
                    cover_y = START_Y + row * 85
                    cover = Image.open(music_picture(music.id)).resize((75, 75))
                    im.alpha_composite(cover, (x, cover_y))
                    im.alpha_composite(table_diff_bg[int(music.lv)], (x - 5, cover_y - 5))
                    tb.draw(x + 56, cover_y + 4, 13, music.id, sbi.t_color[int(music.lv)], 'mm')
                START_Y += (max_row + 1) * 85 + 30

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(picname, 'wb') as f:
                await f.write(by.getbuffer())
            _ntime = int(time.time() - _otime)
            atime += _ntime
            log.info(f'lv.{lv} 定数表更新完成，耗时：{_ntime}s')
        log.info(f'定数表更新完成，共耗时{atime}s')
        return f'定数表更新完成，共耗时{atime}s'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'定数表更新失败，Error: {e}'


async def update_plate_table() -> str:
    """更新完成表"""
    try:
        version = list(_ for _ in plate_to_dx_version.keys())[1:]
        # version.append('霸')
        # version.append('舞')
        rlv: Dict[str, List[Music]] = {}
        for _ in list(reversed(levelList)):
            rlv[_] = []
        if maiApi.config.saveinmem and not ScoreBaseImage.aurora_bg:
            ScoreBaseImage._load_image()
        sbi = ScoreBaseImage if maiApi.config.saveinmem else ScoreBaseImage()
        # 完成表封面边框
        plate_border = Image.open(maimaidir / 'border_table_base.png').convert('RGBA')
        for _v in version:
            if _v in platecn:
                _v = platecn[_v]
            ver, _ver = version_map.get(_v, ([plate_to_dx_version.get(_v)], _v))
            
            music_id_list = mai.total_plate_id_list.get(_ver)
            if not music_id_list:
                log.warning(f'牌子「{_v}」的完成表数据（{_ver}）暂未在服务器提供，已跳过')
                continue
            music = mai.total_list.by_id_list(music_id_list)
            ralv = copy.deepcopy(rlv)

            for m in music:
                ralv[m.level[3]].append(m)

            # 计算高度（仿原项目：START_Y 490 起，逐组累加）
            current_y = 490
            for songs in ralv.values():
                if not songs:
                    continue
                rows = (len(songs) - 1) // 12 + 1
                current_y += rows * 96 + 30
            height = current_y + 180

            im = tricolor_gradient_prism_plus(1400, height)
            
            im.alpha_composite(sbi.aurora_bg)
            im.alpha_composite(sbi.shines_bg, (11, 6))
            im.alpha_composite(sbi.rainbow_bg, (318, height - 545))
            im.alpha_composite(sbi.rainbow_bottom_bg, (122, height - 305))
            for h in range((height // 358) + 1):
                im.alpha_composite(sbi.pattern_bg, (0, (358 + 7) * h))
            # 分隔线
            separator = maimaidir / 'separator.png'
            if separator.exists():
                im.alpha_composite(Image.open(separator).convert('RGBA'), (100, 400))
            # 毛玻璃卡片
            im = generate_frosted_card(im, (50, 444, 1350, height - 120))
            
            dr = ImageDraw.Draw(im)
            fn = DrawText(dr, FOTNEWRODIN)
            tb = DrawText(dr, TBFONT)
            fn.draw(
                700, 
                height - 75, 
                30, 
                f'Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {get_botname()}', 
                sbi.text_color, 
                'mm'
            )
            START_Y = 490
            for r in ralv:
                songs = ralv[r]
                if not songs:
                    continue
                if _v in ['霸', '舞']:
                    songs.sort(key=lambda x: x.ds[-1], reverse=True)
                else:
                    songs.sort(key=lambda x: x.ds[3], reverse=True)
                fn.draw(72, START_Y + 40, 40, r, sbi.text_color, 'lm', 4, (255, 255, 255, 255))
                max_row = 0
                for num, music in enumerate(songs):
                    row, col = divmod(num, 12)
                    max_row = max(max_row, row)
                    x = 180 + col * 96
                    cover_y = START_Y + row * 96
                    cover = music_picture(music.id)
                    im.alpha_composite(Image.open(cover).resize((80, 80)), (x, cover_y))
                    # ID 背景框（使用原项目 border_table_base.png）
                    im.alpha_composite(plate_border, (x - 5, cover_y - 5))
                    # 曲目 ID
                    tb.draw(x + 56, cover_y + 4, 16, music.id, (255, 255, 255, 255), 'mm')
                START_Y += (max_row + 1) * 96 + 30

            by = BytesIO()
            im.save(by, 'PNG')
            async with aiofiles.open(platedir / f'{_v}.png', 'wb') as f:
                await f.write(by.getbuffer())
            log.info(f'{_v}代牌子更新完成')
        return f'完成表更新完成'
    except Exception as e:
        log.error(traceback.format_exc())
        return f'完成表更新失败，Error: {e}'