import math
import traceback
from io import BytesIO
from typing import Dict, List, Optional, Tuple, Union, overload

from PIL import Image, ImageDraw

from .. import *
from .image import DrawText, image_to_base64, music_picture
from .maimaidx_api_data import maiApi
from .maimaidx_error import *
from .maimaidx_model import ChartInfo, PlayInfoDefault, PlayInfoDev, UserInfo
from .maimaidx_music import mai
from .maimaidx_play_result import Collection, dx_star_from_percentage
from .maimaidx_user import ServiceName, Theme


def themed_path(theme: Theme, name: str) -> Path:
    """按主题返回素材路径，主题目录不存在时回退到 mai/pic 根目录。"""
    path = maimaidir / theme.value / name
    if path.exists():
        return path
    return maimaidir / name


def rating_asset_name(rating: int, theme: Theme = Theme.PRISM_PLUS) -> str:
    """按 DX Rating 返回与 B50 页头一致的 Rating 牌素材名。"""
    if rating < 1000:
        num = '01'
    elif rating < 2000:
        num = '02'
    elif rating < 4000:
        num = '03'
    elif rating < 7000:
        num = '04'
    elif rating < 10000:
        num = '05'
    elif rating < 12000:
        num = '06'
    elif rating < 13000:
        num = '07'
    elif rating < 14000:
        num = '08'
    elif rating < 14500:
        num = '09'
    elif rating < 15000:
        num = '10'
    elif theme == Theme.CIRCLE and rating >= 16000:
        num = '12'
    else:
        num = '11'
    return f'UI_CMN_DXRating_{num}.png'


def rating_star_asset_name(rating: int) -> str:
    """返回 Circle 主题 14000 以上 Rating 牌右侧的星标素材名。"""
    from bisect import bisect_right

    thresholds = [
        14000, 14250, 14500, 14750, 15000, 15250,
        15500, 15750, 16000, 16250, 16500, 16750,
    ]
    num_map = [1, 2, 1, 2, 1, 2, 3, 4, 1, 2, 3, 4]
    idx = max(bisect_right(thresholds, rating) - 1, 0)
    return f'UI_CMN_DXRating_Star_0{num_map[idx]}.png'


def dani_plate_asset_name(course_rank: int) -> str:
    """按玩家段位返回与 B50 页头一致的段位牌素材名。"""
    num = course_rank if course_rank <= 10 else course_rank + 1
    return f'UI_DNM_DaniPlate_{num:02d}.png'


def collection_asset_name(asset_type: str, collection_id: int) -> str:
    """返回落雪收藏头像/姓名框对应的素材文件名。"""
    return f'UI_{asset_type.capitalize()}_{collection_id:06d}.png'


def trophy_asset_name(color: Optional[str]) -> str:
    """将称号颜色映射到本地素材，未知颜色回退彩虹称号框。"""
    valid_colors = {'Normal', 'Bronze', 'Silver', 'Gold', 'Rainbow'}
    normalized = str(color or 'Rainbow').capitalize()
    if normalized not in valid_colors:
        normalized = 'Rainbow'
    return f'UI_CMN_Shougou_{normalized}.png'


def format_b50_footer(service: ServiceName) -> str:
    return (
        'Designed by Yuri-YuzuChaN & BlueDeer233. '
        f'Data from {service.value}. Generated by {get_botname()} BOT'
    )


class ScoreBaseImage:
    
    text_color = (124, 129, 255, 255)
    t_color = [
        (255, 255, 255, 255), 
        (255, 255, 255, 255), 
        (255, 255, 255, 255), 
        (255, 255, 255, 255), 
        (138, 0, 226, 255)
    ]
    id_color = [
        (129, 217, 85, 255), 
        (245, 189, 21, 255),  
        (255, 129, 141, 255), 
        (159, 81, 220, 255),
        (138, 0, 226, 255)
    ]
    bg_color = [
        (111, 212, 61, 255), 
        (248, 183, 9, 255), 
        (255, 129, 141, 255), 
        (159, 81, 220, 255), 
        (219, 170, 255, 255)
    ]
    id_diff = [Image.new('RGBA', (55, 10), color) for color in bg_color]
    
    _diff = []
    _rise = []
    title_bg = None
    title_lengthen_bg = None
    design_bg = None
    aurora_bg = None
    shines_bg = None
    pattern_bg = None
    rainbow_bg = None
    rainbow_bottom_bg = None
    # 主题相关素材的内存缓存：{(theme, name): Image}
    _themed_images: Dict[Tuple[str, str], Image.Image] = {}

    @classmethod
    def _open_themed(cls, theme: Theme, name: str) -> Image.Image:
        key = (theme.value, name)
        if maiApi.config.saveinmem:
            img = cls._themed_images.get(key)
            if img is None:
                img = Image.open(themed_path(theme, name))
                cls._themed_images[key] = img
            return img
        return Image.open(themed_path(theme, name))

    @classmethod
    def _load_image(cls):
        cls._diff = [
            Image.open(maimaidir / 'b50_score_basic.png'), 
            Image.open(maimaidir / 'b50_score_advanced.png'), 
            Image.open(maimaidir / 'b50_score_expert.png'), 
            Image.open(maimaidir / 'b50_score_master.png'), 
            Image.open(maimaidir / 'b50_score_remaster.png')
        ]
        cls._rise = [
            Image.open(maimaidir / 'rise_score_basic.png'),
            Image.open(maimaidir / 'rise_score_advanced.png'),
            Image.open(maimaidir / 'rise_score_expert.png'),
            Image.open(maimaidir / 'rise_score_master.png'),
            Image.open(maimaidir / 'rise_score_remaster.png')
        ]
        # 默认主题素材（供完成表/上分推荐等非个性化绘图使用）
        default = Theme.PRISM_PLUS
        cls.title_bg = cls._open_themed(default, 'title.png')
        cls.title_lengthen_bg = cls._open_themed(default, 'title_lengthen.png')
        cls.design_bg = cls._open_themed(default, 'design.png')
        cls.aurora_bg = Image.open(maimaidir / 'aurora.png').convert('RGBA')
        cls.shines_bg = Image.open(maimaidir / 'bg_shines.png').convert('RGBA')
        cls.pattern_bg = Image.open(maimaidir / 'pattern.png')
        cls.rainbow_bg = Image.open(maimaidir / 'rainbow.png').convert('RGBA')
        cls.rainbow_bottom_bg = Image.open(maimaidir / 'rainbow_bottom.png').convert('RGBA')
    
    
    def __init__(
        self,
        image: Image.Image = None,
        theme: Theme = Theme.PRISM_PLUS,
    ) -> None:
        self.theme = theme
        self.text_color = theme.color
        if not maiApi.config.saveinmem:
            self.load_image()
        elif not self._diff:
            self._load_image()
        # 按当前主题加载个性化素材
        self.title_bg = self._open_themed(theme, 'title.png')
        self.title_lengthen_bg = self._open_themed(theme, 'title_lengthen.png')
        self.design_bg = self._open_themed(theme, 'design.png')
        self._im = image
        if image is not None:
            dr = ImageDraw.Draw(self._im)
            self._sy = DrawText(dr, SIYUAN)
            self._tb = DrawText(dr, TBFONT)
    
    def load_image(self):
        self._diff = [
            Image.open(maimaidir / 'b50_score_basic.png'), 
            Image.open(maimaidir / 'b50_score_advanced.png'), 
            Image.open(maimaidir / 'b50_score_expert.png'), 
            Image.open(maimaidir / 'b50_score_master.png'), 
            Image.open(maimaidir / 'b50_score_remaster.png')
        ]
        self._rise = [
            Image.open(maimaidir / 'rise_score_basic.png'),
            Image.open(maimaidir / 'rise_score_advanced.png'),
            Image.open(maimaidir / 'rise_score_expert.png'),
            Image.open(maimaidir / 'rise_score_master.png'),
            Image.open(maimaidir / 'rise_score_remaster.png')
        ]
        self.aurora_bg = Image.open(maimaidir / 'aurora.png').convert('RGBA')
        self.shines_bg = Image.open(maimaidir / 'bg_shines.png').convert('RGBA')
        self.pattern_bg = Image.open(maimaidir / 'pattern.png')
        self.rainbow_bg = Image.open(maimaidir / 'rainbow.png').convert('RGBA')
        self.rainbow_bottom_bg = Image.open(maimaidir / 'rainbow_bottom.png').convert('RGBA')
    
    def whiledraw(
        self, 
        data: Union[List[ChartInfo], List[PlayInfoDefault], List[PlayInfoDev]], 
        best: bool, 
        height: int = 0
    ) -> None:
        """
        循环绘制成绩
        
        Params:
            `data`: 数据
            `dx`: 是否为新版本成绩
            `height`: 起始高度
        """
        # 确保图片资源已加载
        if not self._diff:
            self._load_image()
        
        # y为第一排纵向坐标，dy为各行间距
        dy = 114
        if data and type(data[0]) == ChartInfo:
            y = 235 if best else 1085
        else:
            y = height
        for num, info in enumerate(data):
            if num % 5 == 0:
                x = 16
                y += dy if num != 0 else 0
            else:
                x += 276

            # 检查 level_index 是否在有效范围内 (0-4)
            if not hasattr(info, 'level_index') or info.level_index < 0 or info.level_index >= len(self._diff):
                log.warning(f'无效的 level_index: {getattr(info, "level_index", None)} for song {getattr(info, "song_id", "unknown")}')
                continue

            cover = Image.open(music_picture(info.song_id)).resize((75, 75))
            version = Image.open(maimaidir / f'{info.type.upper()}.png').resize((37, 14))
            if info.rate.islower():
                rank_name = f'UI_TTR_Rank_{score_Rank_l[info.rate]}.png'
            else:
                rank_name = f'UI_TTR_Rank_{info.rate}.png'
            rate = Image.open(themed_path(self.theme, rank_name)).resize((63, 28))

            self._im.alpha_composite(self._diff[info.level_index], (x, y))
            self._im.alpha_composite(cover, (x + 12, y + 12))
            self._im.alpha_composite(version, (x + 51, y + 91))
            self._im.alpha_composite(rate, (x + 92, y + 78))
            if info.fc:
                fc = Image.open(maimaidir / f'UI_MSS_MBase_Icon_{fcl[info.fc]}.png').resize((34, 34))
                self._im.alpha_composite(fc, (x + 154, y + 77))
            if info.fs:
                fs = Image.open(maimaidir / f'UI_MSS_MBase_Icon_{fsl[info.fs]}.png').resize((34, 34))
                self._im.alpha_composite(fs, (x + 185, y + 77))
            
            # 安全获取歌曲信息和谱面数据，防止 IndexError
            difficulty = mai.get_difficulty(info.song_id, info.level_index)
            if difficulty:
                dxscore = difficulty.dx_score
            else:
                # 如果无法获取谱面数据，使用默认值或跳过 DX 分数显示
                dxscore = 0
                log.warning(f'无法获取歌曲 {info.song_id} 的谱面数据 (level_index: {info.level_index})')
            
            dxnum = dxScore(info.dxScore / dxscore * 100) if dxscore > 0 else 0
            if dxnum:
                self._im.alpha_composite(
                    Image.open(maimaidir / f'UI_GAM_Gauge_DXScoreIcon_0{dxnum}.png').resize((47, 26)), (x + 217, y + 80)
                )

            self._tb.draw(x + 26, y + 98, 13, info.song_id, self.id_color[info.level_index], anchor='mm')
            title = info.title
            if coloumWidth(title) > 18:
                title = changeColumnWidth(title, 17) + '...'
            self._sy.draw(x + 93, y + 14, 14, title, self.t_color[info.level_index], anchor='lm')
            self._tb.draw(x + 93, y + 38, 30, f'{info.achievements:.4f}%', self.t_color[info.level_index], anchor='lm')
            self._tb.draw(x + 219, y + 65, 15, f'{info.dxScore}/{dxscore}', self.t_color[info.level_index], anchor='mm')
            self._tb.draw(x + 93, y + 65, 15, f'{info.ds} -> {info.ra}', self.t_color[info.level_index], anchor='lm')


class DrawBest(ScoreBaseImage):

    def __init__(
        self,
        UserInfo: UserInfo,
        qqid: Optional[Union[int, str]] = None,
        theme: Theme = Theme.PRISM_PLUS,
        all_perfect: bool = False,
        min_dx_star: Optional[int] = None,
        fitted: bool = False,
        all_perfect_plus: bool = False,
        achievement_mode: Optional[str] = None,
        difficulty_index: Optional[int] = None,
        all_songs: bool = False,
        player=None,
        service: ServiceName = ServiceName.DIVINGFISH,
    ) -> None:
        bg = themed_path(theme, 'b50.png')
        super().__init__(Image.open(bg).convert('RGBA'), theme)
        self.userName = UserInfo.nickname
        self.plate = UserInfo.plate
        self.addRating = UserInfo.additional_rating
        self.Rating = UserInfo.rating
        self.sdBest = UserInfo.charts.sd
        self.dxBest = UserInfo.charts.dx
        self.qqid = qqid
        self.all_perfect = all_perfect
        self.min_dx_star = min_dx_star
        self.fitted = fitted
        self.all_perfect_plus = all_perfect_plus
        self.achievement_mode = achievement_mode
        self.difficulty_index = difficulty_index
        self.all_songs = all_songs
        self.player = player
        self.service = service

    @classmethod
    def from_best50(
        cls,
        player,
        best50,
        qqid: Optional[Union[int, str]] = None,
        theme: Theme = Theme.PRISM_PLUS,
        all_perfect: bool = False,
        min_dx_star: Optional[int] = None,
        fitted: bool = False,
        all_perfect_plus: bool = False,
        achievement_mode: Optional[str] = None,
        difficulty_index: Optional[int] = None,
        all_songs: bool = False,
        service: ServiceName = ServiceName.DIVINGFISH,
    ) -> 'DrawBest':
        """从统一 Player + Best50 构建绘图对象。"""
        from .maimaidx_play_result import best50_to_userinfo

        return cls(
            best50_to_userinfo(player, best50),
            qqid=qqid,
            theme=theme,
            all_perfect=all_perfect,
            min_dx_star=min_dx_star,
            fitted=fitted,
            all_perfect_plus=all_perfect_plus,
            achievement_mode=achievement_mode,
            difficulty_index=difficulty_index,
            all_songs=all_songs,
            player=player,
            service=service,
        )

    def _findRaPic(self) -> str:
        """
        寻找指定的Rating图片
        
        Returns:
            `str` 返回图片名称
        """
        return rating_asset_name(self.Rating, self.theme)

    def _raPicStar(self) -> str:
        """CIRCLE 主题高分段星标"""
        return rating_star_asset_name(self.Rating)

    def _findMatchLevel(self) -> str:
        """
        寻找匹配等级图片
        
        Returns:
            `str` 返回图片名称
        """
        return dani_plate_asset_name(self.addRating)

    async def _collection_asset(
        self,
        asset_type: str,
        collection: Optional[Collection],
    ) -> Optional[Union[BytesIO, Path]]:
        if collection is None:
            return None
        file_name = collection_asset_name(asset_type, collection.id)
        local_path = mai_dir / asset_type / file_name
        if local_path.exists():
            return local_path
        if not maiApi.config.assets_online:
            return None

        content = await maiApi.online_asset(asset_type, file_name)
        if not content:
            return None
        try:
            local_path.parent.mkdir(parents=True, exist_ok=True)
            local_path.write_bytes(content)
            return local_path
        except OSError:
            return BytesIO(content)

    async def draw(self) -> Image.Image:
        
        logo = Image.open(themed_path(self.theme, 'logo.png')).resize((249, 120))
        Name = Image.open(maimaidir / 'Name.png')
        course_rank = self.player.course_rank if self.player else self.addRating
        match_path = maimaidir / dani_plate_asset_name(course_rank)
        if not match_path.exists():
            match_path = maimaidir / 'UI_DNM_DaniPlate_00.png'
        MatchLevel = Image.open(match_path).resize((80, 32))

        class_rank = self.player.class_rank if self.player else 0
        class_path = maimaidir / f'UI_FBR_Class_{class_rank:02d}.png'
        if not class_path.exists():
            class_path = maimaidir / 'UI_FBR_Class_00.png'
        ClassLevel = Image.open(class_path).resize((90, 54))

        self._im.alpha_composite(logo, (14, 60))
        name_plate = self.player.name_plate if self.player else self.plate
        if isinstance(name_plate, Collection):
            plate_path = await self._collection_asset('plate', name_plate)
            if plate_path is None:
                plate_path = resolve_plate_asset(None)
        else:
            plate_path = resolve_plate_asset(name_plate)
            if name_plate and plate_path.name == 'UI_Plate_550101.png':
                log.warning(
                    f'未找到姓名框素材「{name_plate}」'
                    f'→「{normalize_plate_filename(name_plate)}」，使用默认姓名框'
                )
        plate = Image.open(plate_path).resize((800, 130))
        self._im.alpha_composite(plate, (300, 60))

        icon_path = await self._collection_asset(
            'icon', self.player.icon if self.player else None
        )
        if icon_path is not None:
            icon = Image.open(icon_path).convert('RGBA').resize((120, 120))
        elif self.qqid:
            try:
                qq_logo = await maiApi.qqlogo(qqid=self.qqid)
                icon = Image.open(BytesIO(qq_logo)).convert('RGBA').resize((120, 120))
            except Exception:
                icon = Image.open(maimaidir / 'UI_Icon_509506.png').resize((120, 120))
        else:
            icon = Image.open(maimaidir / 'UI_Icon_509506.png').resize((120, 120))
        self._im.alpha_composite(icon, (305, 65))

        dx_rating_size = (186, 35)
        dx_rating_star = None
        rating_num_x = 520
        rating_num_y = 80
        rating_num_gap = 15
        rating_num_size = (17, 20)
        if self.theme == Theme.CIRCLE and self.Rating >= 14000:
            dx_rating_size = (170, 35)
            dx_rating_star = Image.open(
                themed_path(self.theme, self._raPicStar())
            ).resize((21, 35))
            rating_num_x = 515
            rating_num_y = 82
            rating_num_gap = 13
            rating_num_size = (14, 17)

        dx_rating = Image.open(themed_path(self.theme, self._findRaPic())).resize(dx_rating_size)
        self._im.alpha_composite(dx_rating, (435, 72))
        if dx_rating_star is not None:
            self._im.alpha_composite(dx_rating_star, (590, 72))

        Rating = f'{self.Rating:05d}'
        for n, i in enumerate(Rating):
            self._im.alpha_composite(
                Image.open(maimaidir / f'UI_NUM_Drating_{i}.png').resize(rating_num_size),
                (rating_num_x + rating_num_gap * n, rating_num_y),
            )
        self._im.alpha_composite(Name, (435, 115))
        self._im.alpha_composite(MatchLevel, (625, 120))
        self._im.alpha_composite(ClassLevel, (620, 60))

        player_name = self.player.name if self.player else self.userName
        self._sy.draw(445, 135, 20, player_name, (0, 0, 0, 255), 'lm')
        sdrating, dxrating = sum([_.ra for _ in self.sdBest]), sum([_.ra for _ in self.dxBest])
        trophy = self.player.trophy if self.player else None
        if trophy:
            summary = trophy.name
            rating_path = shougou_dir / trophy_asset_name(trophy.color)
            summary_drawer = self._sy
            summary_size = 14
        else:
            summary = format_best50_summary(
                sdrating,
                dxrating,
                self.Rating,
                all_perfect=self.all_perfect,
                min_dx_star=self.min_dx_star,
                fitted=self.fitted,
                all_perfect_plus=self.all_perfect_plus,
                achievement_mode=self.achievement_mode,
                difficulty_index=self.difficulty_index,
                all_songs=self.all_songs,
            )
            rating_path = shougou_dir / 'UI_CMN_Shougou_Rainbow.png'
            # Torus 不包含中文字形；仅在汇总中出现中文标签时切换中文字体。
            summary_drawer = (
                self._sy
                if any('\u4e00' <= char <= '\u9fff' for char in summary)
                else self._tb
            )
            summary_size = 17
        if not rating_path.exists():
            rating_path = maimaidir / 'UI_CMN_Shougou_Rainbow.png'
        rating = Image.open(rating_path).resize((270, 27))
        self._im.alpha_composite(rating, (435, 160))
        summary_drawer.draw(
            570, 172, summary_size,
            summary,
            (0, 0, 0, 255), 'mm', 3, (255, 255, 255, 255)
        )
        self._sy.draw(
            700, 1570, 22,
            format_b50_footer(self.service),
            self.text_color, 'mm', 5, (255, 255, 255, 255)
        )

        if self.all_songs:
            self.whiledraw(self.sdBest + self.dxBest, True)
        else:
            self.whiledraw(self.sdBest, True)
            self.whiledraw(self.dxBest, False)

        return self._im


def format_best50_summary(
    old_rating: int,
    new_rating: int,
    total_rating: int,
    *,
    all_perfect: bool = False,
    min_dx_star: Optional[int] = None,
    fitted: bool = False,
    all_perfect_plus: bool = False,
    achievement_mode: Optional[str] = None,
    difficulty_index: Optional[int] = None,
    all_songs: bool = False,
) -> str:
    """生成普通或筛选模式 B50 图片顶部的 Rating 汇总文字。"""
    if all_songs:
        return f'(全曲)B50: {total_rating}'
    if all_perfect:
        label = '(ap)'
    elif all_perfect_plus:
        label = '(ap+)'
    elif fitted:
        label = '(拟合)'
    elif min_dx_star is not None:
        label = f'({min_dx_star}星)'
    elif achievement_mode is not None:
        labels = {
            'under_s': '(越级)',
            'near': '(寸)',
            'lock': '(锁血)',
        }
        if achievement_mode not in labels:
            raise ValueError(f'未知的达成率筛选模式：{achievement_mode}')
        label = labels[achievement_mode]
    elif difficulty_index is not None:
        labels = ('绿谱', '黄谱', '红谱', '紫谱', '白谱')
        if not 0 <= difficulty_index < len(labels):
            raise ValueError('谱面难度索引必须在 0 到 4 之间')
        label = f'({labels[difficulty_index]})'
    else:
        label = ''
    return (
        f'{label}B35: {old_rating} + '
        f'B15: {new_rating} = {total_rating}'
    )


def dxScore(dx: int) -> int:
    """
    获取DX评分星星数量
    
    Params:
        `dx`: dx百分比
    Returns:
        `int` 返回星星数量
    """
    return dx_star_from_percentage(dx)


def getCharWidth(o: int) -> int:
    widths = [
        (126, 1), (159, 0), (687, 1), (710, 0), (711, 1), (727, 0), (733, 1), (879, 0), (1154, 1), (1161, 0),
        (4347, 1), (4447, 2), (7467, 1), (7521, 0), (8369, 1), (8426, 0), (9000, 1), (9002, 2), (11021, 1),
        (12350, 2), (12351, 1), (12438, 2), (12442, 0), (19893, 2), (19967, 1), (55203, 2), (63743, 1),
        (64106, 2), (65039, 1), (65059, 0), (65131, 2), (65279, 1), (65376, 2), (65500, 1), (65510, 2),
        (120831, 1), (262141, 2), (1114109, 1),
    ]
    if o == 0xe or o == 0xf:
        return 0
    for num, wid in widths:
        if o <= num:
            return wid
    return 1


def coloumWidth(s: str) -> int:
    res = 0
    for ch in s:
        res += getCharWidth(ord(ch))
    return res


def changeColumnWidth(s: str, len: int) -> str:
    res = 0
    sList = []
    for ch in s:
        res += getCharWidth(ord(ch))
        if res <= len:
            sList.append(ch)
    return ''.join(sList)


@overload
def computeRa(ds: float, achievement: float) -> int:
    """
    计算底分
    
    Params:
        `ds`: 定数
        `achievement`: 成绩
    Returns:
        返回底分
    """
@overload
def computeRa(ds: float, achievement: float, *, onlyrate: bool = False) -> str:
    """
    计算评价
    
    Params:
        `ds`: 定数
        `achievement`: 成绩
        `onlyrate`: 是否只返回评价
    Returns:
        返回评价
    """
@overload
def computeRa(ds: float, achievement: float, *, israte: bool = False) -> Tuple[int, str]:
    """
    计算底分和评价
    
    Params:
        `ds`: 定数
        `achievement`: 成绩
        `israte`: 是否返回所有数据
    Returns:
        (底分, 评价)
    """
def computeRa(
    ds: float, 
    achievement: float, 
    *, 
    onlyrate: bool = False, 
    israte: bool = False
) -> Union[int, Tuple[int, str]]:
    if achievement < 50:
        baseRa = 7.0
        rate = 'D'
    elif achievement < 60:
        baseRa = 8.0
        rate = 'C'
    elif achievement < 70:
        baseRa = 9.6
        rate = 'B'
    elif achievement < 75:
        baseRa = 11.2
        rate = 'BB'
    elif achievement < 80:
        baseRa = 12.0
        rate = 'BBB'
    elif achievement < 90:
        baseRa = 13.6
        rate = 'A'
    elif achievement < 94:
        baseRa = 15.2
        rate = 'AA'
    elif achievement < 97:
        baseRa = 16.8
        rate = 'AAA'
    elif achievement < 98:
        baseRa = 20.0
        rate = 'S'
    elif achievement < 99:
        baseRa = 20.3
        rate = 'Sp'
    elif achievement < 99.5:
        baseRa = 20.8
        rate = 'SS'
    elif achievement < 100:
        baseRa = 21.1
        rate = 'SSp'
    elif achievement < 100.5:
        baseRa = 21.6
        rate = 'SSS'
    else:
        baseRa = 22.4
        rate = 'SSSp'

    if israte:
        data = (math.floor(ds * (min(100.5, achievement) / 100) * baseRa), rate)
    elif onlyrate:
        data = rate
    else:
        data = math.floor(ds * (min(100.5, achievement) / 100) * baseRa)

    return data


async def generate(
    qqid: Optional[int] = None,
    username: Optional[str] = None,
    all_perfect: bool = False,
    min_dx_star: Optional[int] = None,
    fitted: bool = False,
    all_perfect_plus: bool = False,
    achievement_mode: Optional[str] = None,
    difficulty_index: Optional[int] = None,
    all_songs: bool = False,
) -> Union[MessageSegment, str]:
    """
    生成b50
    
    Params:
        `qqid`: QQ号
        `username`: 用户名
        `all_perfect`: 是否为 ap50
        `min_dx_star`: DX SCORE 最低星级（1～5）
        `fitted`: 是否用谱面拟合定数重算 B50
        `all_perfect_plus`: 是否只保留玩家实际 AP+ 成绩
        `achievement_mode`: 达成率筛选模式
        `difficulty_index`: 谱面难度索引（0～4）
        `all_songs`: 是否忽略新旧曲分类并选取 Rating 最高的 50 项
    Returns:
        `Union[MessageSegment, str]`
    """
    from .maimaidx_lxns import LxnsError
    from .maimaidx_source import get_best50, get_service
    try:
        from .maimaidx_user import Theme, userstore

        if username:
            qqid = None
            theme = Theme.PRISM_PLUS
        else:
            theme = userstore.get(qqid).theme if qqid else Theme.PRISM_PLUS
        player, best50 = await get_best50(
            qqid=qqid,
            username=username,
            all_perfect=all_perfect,
            min_dx_star=min_dx_star,
            fitted=fitted,
            all_perfect_plus=all_perfect_plus,
            achievement_mode=achievement_mode,
            difficulty_index=difficulty_index,
            all_songs=all_songs,
        )
        service = get_service(qqid, username)
        draw_best = DrawBest.from_best50(
            player,
            best50,
            qqid=qqid,
            theme=theme,
            all_perfect=all_perfect,
            min_dx_star=min_dx_star,
            fitted=fitted,
            all_perfect_plus=all_perfect_plus,
            achievement_mode=achievement_mode,
            difficulty_index=difficulty_index,
            all_songs=all_songs,
            service=service,
        )

        msg = MessageSegment.image(image_to_base64(await draw_best.draw()))
    except (
        UserNotFoundError,
        UserNotExistsError,
        UserDisabledQueryError,
        TokenError,
        TokenDisableError,
        TokenNotFoundError,
        LxnsError,
    ) as e:
        msg = str(e)
    except Exception as e:
        log.error(traceback.format_exc())
        msg = f'未知错误：{type(e)}\n请联系Bot管理员'
    return msg
